// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzxrmr8tTdTrl8ubaP6bPD0WItTIXSvc',
    appId: '1:470021759844:web:176fe8185a61ec64df9071',
    messagingSenderId: '470021759844',
    projectId: 'travelapp-flutter-ad344',
    authDomain: 'travelapp-flutter-ad344.firebaseapp.com',
    storageBucket: 'travelapp-flutter-ad344.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA41mnWFoQiZJxbvXZ6RePJqRo4A8veD-U',
    appId: '1:470021759844:android:ae5eeb0c114c1276df9071',
    messagingSenderId: '470021759844',
    projectId: 'travelapp-flutter-ad344',
    storageBucket: 'travelapp-flutter-ad344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbC-GtVNYvDvW3peBRIm4VUov0f_5PjE',
    appId: '1:470021759844:ios:5b92e7c0dd4442fddf9071',
    messagingSenderId: '470021759844',
    projectId: 'travelapp-flutter-ad344',
    storageBucket: 'travelapp-flutter-ad344.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPbC-GtVNYvDvW3peBRIm4VUov0f_5PjE',
    appId: '1:470021759844:ios:5b92e7c0dd4442fddf9071',
    messagingSenderId: '470021759844',
    projectId: 'travelapp-flutter-ad344',
    storageBucket: 'travelapp-flutter-ad344.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTzxrmr8tTdTrl8ubaP6bPD0WItTIXSvc',
    appId: '1:470021759844:web:d33ea7c0f4e51073df9071',
    messagingSenderId: '470021759844',
    projectId: 'travelapp-flutter-ad344',
    authDomain: 'travelapp-flutter-ad344.firebaseapp.com',
    storageBucket: 'travelapp-flutter-ad344.firebasestorage.app',
  );
}
